name = "gym-tracker"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
TZ = "America/Santiago"
SESSION_VERSION = "1"
EMAIL_TO = "omar.pache@gmail.com"
